import {ms, s, vs, ScaledSheet} from 'react-native-size-matters';
import {colorPalates, fonts} from 'theme';
import {StyleSheet} from 'react-native';
import colors from '../../../../theme/colors/colors';

export const styles = ScaledSheet.create({
  container: {
    flex: 1,
  },
  map: {...StyleSheet.absoluteFillObject},
  searchBtn: {
    position: 'absolute',
    zIndex: 1000,
    backgroundColor: colorPalates.white,
    padding: ms(10),
    borderRadius: ms(20),
    alignSelf: 'center',
    top: 20,
  },
  searchText: {
    fontSize: ms(10),
    fontFamily: fonts.primaryBoldFont,
    color: colorPalates.black,
  },

  item: {
    position: 'absolute',
    alignSelf: 'center',
    top: '13%',
    flexDirection: 'row',
    backgroundColor: colorPalates.white,
    borderRadius: ms(10),
    alignItems: 'center',
    marginVertical: vs(10),
    maxWidth: s(320),
    marginHorizontal: s(16),
    minHeight: vs(130),
  },
  imgContainer: {
    width: '50%',
    height: '100%',
    borderRadius: ms(10),
  },
  image: {
    width: '100%',
    height: '100%',
    borderRadius: ms(10),
  },
  content: {
    width: '50%',
    height: '100%',
    borderRadius: ms(10),
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    padding: ms(5),
  },
  name: {
    maxWidth: '100%',
    fontSize: ms(16),
    fontFamily: fonts.primaryMediumFont,
    color: colorPalates.blackShade02,
    fontWeight: '500',
    marginBottom: vs(5),
  },
  star: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: vs(5),
  },
  rate: {
    fontSize: 16,
    color: colorPalates.grayShade80,
    marginLeft: ms(5),
  },
  likecontainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: vs(5),
  },
  smallText: {
    fontFamily: fonts.primaryRegularFont,
    color: colorPalates.black,
    fontSize: ms(12),
    marginBottom: vs(5),
  },
  like: {
    fontFamily: fonts.primaryMediumFont,
    marginHorizontal: s(8),
    fontSize: ms(13),
    color: colorPalates.grayShade80,
  },
  card: {
    width: '100%',
    fontSize: ms(13),
    color: colorPalates.blackShade02,
    fontFamily: fonts.primaryMediumFont,
    fontWeight: '500',
    marginBottom: vs(8),
  },
  icon: {width: ms(18), height: ms(18)},
  iconMedium: {width: ms(22), height: ms(22)},
  imageView: {
    width: vs(80),
    height: vs(80),
    borderRadius: ms(10),
    marginLeft: s(5),
  },
  imageListStyle: {
    width: '100%',
  },
  nameText: {
    color: colors.blackShade02,
    fontFamily: fonts.primaryMediumFont,
    fontSize: ms(18),
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: s(2),
  },
  dotView: {
    width: vs(2),
    height: vs(2),
    marginHorizontal: s(3),
    backgroundColor: colors.grayShade80,
    borderRadius: ms(300),
    alignSelf: 'center',
  },
  btnContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  directionBtn: {
    padding: s(10),
    backgroundColor: colors.greenShade60,
    borderRadius: ms(20),
    paddingHorizontal: s(15),
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginRight: s(10),
    borderColor: colors.greenShade60,
    borderWidth: 1,
    elevation: 5,
  },
  directionBtnText: {
    color: colors.white,
    fontSize: ms(13),
    marginLeft: s(10),
  },
  directionsIcon: {
    width: ms(16),
    height: ms(16),
    tintColor: colors.white,
  },
  ratingText: {
    color: colors.grayShade8F,
    fontFamily: fonts.primaryMediumFont,
    fontSize: ms(13),
    marginRight: s(5),
  },
  storeText: {
    color: colors.grayShade8F,
    fontFamily: fonts.primaryMediumFont,
    fontSize: ms(13),
  },
  textList: {
    marginVertical: ms(5),
    position: 'absolute',
    bottom: 0,
    paddingHorizontal: s(10),
  },
  popUpContainer: {
    flexDirection: 'row',
    backgroundColor: colors.white,
    borderRadius: ms(10),
    position: 'absolute',
    top: '13%',
    marginVertical: vs(10),
    maxWidth: s(320),
    marginHorizontal: s(16),
    minHeight: vs(125),
    alignItems: 'center',
    paddingHorizontal: ms(10),
  },
  imagePlaceStyle: {
    width: vs(95),
    height: vs(80),
    borderRadius: ms(10),
    marginBottom: s(20),
  },
  loaderStyle: {
    width: vs(95),
    height: vs(95),
    right: 10,
  },
  modalCOntainer: {
    paddingVertical: s(10),
    height: '100%',
    flex: 1,
    marginTop: s(10),
  },
});
