import svg from '../../theme/images/svg';

export const IMData = [
  {
    name: 'Dispensary',
    white: svg.WhiteDispensary,
    green: svg.GreenDispensary,
    svgName: 'GreenDispensary',
    id: '1',
  },
  {
    name: 'Delivery',
    white: svg.WhiteDelivery,
    green: svg.GreenDelivery,
    svgName: 'GreenDelivery',
    id: '2',
  },
  {
    name: 'MMJ Doc',
    white: svg.WhiteMMJDoc,
    green: svg.GreenMMJDoc,
    svgName: 'GreenMMJDoc',
    id: '3',
  },
  {
    name: 'Cannabis Brand',
    white: svg.WhiteCannabisBrand,
    green: svg.GreenCannabisBrand,
    svgName: 'GreenCannabisBrand',
    id: '4',
  },
  {
    name: 'Grower',
    white: svg.WhiteGrower,
    green: svg.GreenGrower,
    svgName: 'GreenGrower',
    id: '5',
  },
  {
    name: 'Canna Biz',
    white: svg.WhiteCannabisBrand,
    green: svg.GreenCannabisBrand,
    svgName: 'GreenCannabisBrand',
    id: '6',
  },
  {
    name: '420 Events Organizer',
    white: svg.White420EventOrganizer,
    green: svg.Green420EventOrganizer,
    svgName: 'Green420EventOrganizer',
    id: '7',
  },
  {
    name: 'Smoke Lounge',
    white: svg.WhiteSmokeLounge,
    green: svg.GreenSmokeLounge,
    svgName: 'GreenSmokeLounge',
    id: '8',
  },
  {
    name: 'Night Club',
    white: svg.WhiteNightClub,
    green: svg.GreenNightClub,
    svgName: 'GreenNightClub',
    id: '9',
  },
  {
    name: 'Bar',
    white: svg.WhiteBar,
    green: svg.GreenBar,
    svgName: 'GreenBar',
    id: '10',
  },
  {
    name: 'Artist',
    white: svg.WhiteArtist,
    green: svg.GreenArtist,
    svgName: 'GreenArtist',
    id: '12',
  },
  {
    name: 'Musician',
    white: svg.WhiteMusician,
    green: svg.GreenMusician,
    svgName: 'GreenMusician',
    id: '12',
  },
  {
    name: 'Entrepreneur',
    white: svg.WhiteEntertainer,
    green: svg.GrenEntertainer,
    svgName: 'GrenEntertainer',
    id: '13',
  },
  {
    name: 'Writer',
    white: svg.WhiteWriter,
    green: svg.GreenWriter,
    svgName: 'GreenWriter',
    id: '14',
  },
  {
    name: 'Influencer',
    white: svg.WhiteInfluencer,
    green: svg.GreenInfluencer,
    svgName: 'GreenInfluencer',
    id: '15',
  },
  {
    name: 'Gamer',
    white: svg.WhiteGamer,
    green: svg.GreenGamer,
    svgName: 'GreenGamer',
    id: '16',
  },
  {
    name: 'Restaurant',
    white: svg.WhiteRestaurant,
    green: svg.GreenRestaurant,
    svgName: 'GreenRestaurant',
    id: '17',
  },
  {
    name: 'Photographer',
    white: svg.WhitePhotographer,
    green: svg.GreenPhotographer,
    svgName: 'GreenPhotographer',
    id: '18',
  },
  {
    name: 'Athlete',
    white: svg.WhiteAthlete,
    green: svg.GreenAthlete,
    svgName: 'GreenAthlete',
    id: '19',
  },
  {
    name: 'Model',
    white: svg.WhiteModel,
    green: svg.GreenModel,
    svgName: 'GreenModel',
    id: '20',
  },
  {
    name: 'DJ',
    white: svg.WhiteDj,
    green: svg.GreenDj,
    svgName: 'GreenDj',
    id: '21',
  },
  {
    name: 'Dancer',
    white: svg.WhiteDancer,
    green: svg.GreenDancer,
    svgName: 'GreenDancer',
    id: '22',
  },
  {
    name: 'Videographer',
    white: svg.WhiteVideographer,
    green: svg.GreenVideographer,
    svgName: 'GreenVideographer',
    id: '23',
  },
  {
    name: 'Chef',
    white: svg.WhiteChef,
    green: svg.GreenChef,
    svgName: 'GreenChef',
    id: '24',
  },
  {
    name: 'Entertainer',
    white: svg.WhiteEntertainer,
    green: svg.GrenEntertainer,
    svgName: 'GrenEntertainer',
    id: '25',
  },
  {
    name: 'Prankster',
    white: svg.WhitePrankster,
    green: svg.GreenPrankster,
    svgName: 'GreenPrankster',
    id: '26',
  },
  {
    name: 'Actor',
    white: svg.WhiteActor,
    green: svg.GreenActor,
    svgName: 'GreenActor',
    id: '27',
  },
  {
    name: 'Designer',
    white: svg.WhiteDesigner,
    green: svg.GreenDesigner,
    svgName: 'GreenDesigner',
    id: '28',
  },
  {
    name: 'Performing artist',
    white: svg.WhitePerformingArtist,
    green: svg.GreenPerformingArtist,
    svgName: 'GreenPerformingArtist',
    id: '29',
  },
  {
    name: 'Smoker',
    white: svg.WhiteSmoker,
    green: svg.GreenSmoker,
    svgName: 'GreenSmoker',
    id: '30',
  },
  {
    name: 'Joker',
    white: svg.WhiteJoker,
    green: svg.GreenJoker,
    svgName: 'GreenJoker',
    id: '31',
  },
  {
    name: 'Midnight Toker',
    white: svg.WhiteMidnightToker,
    green: svg.GreenMidnightToker,
    svgName: 'GreenMidnightToker',
    id: '32',
  },
];

export const CANNABIS = [
  {
    name: 'INDICA',
    white: svg.WhiteIndica,
    green: svg.GreenIndica,
    svgName: 'GreenIndica',
    id: '33',
  },
  {
    name: 'SATIVA',
    white: svg.WhiteSativa,
    green: svg.GreenSativa,
    svgName: 'GreenSativa',
    id: '34',
  },
  {
    name: 'HYBRID',
    white: svg.WhiteHybrid,
    green: svg.GreenHybrid,
    svgName: 'GreenHybrid',
    id: '35',
  },
  {
    name: 'CONCENTRATES',
    white: svg.WhiteConcentrates,
    green: svg.GreenConcentrates,
    svgName: 'GreenConcentrates',
    id: '36',
  },
  {
    name: 'CBD',
    white: svg.WhiteCbd,
    green: svg.GreenCbd,
    svgName: 'GreenCbd',
    id: '37',
  },
  {
    name: 'HEMP',
    white: svg.WhiteHemp,
    green: svg.GreenHemp,
    svgName: 'GreenHemp',
    id: '38',
  },
  {
    name: 'FLOWER',
    white: svg.WhiteFlower,
    green: svg.GreenFlower,
    svgName: 'GreenFlower',
    id: '39',
  },
  {
    name: 'VAPE',
    white: svg.WhiteVape,
    green: svg.GreenVape,
    svgName: 'GreenVape',
    id: '40',
  },
  {
    name: 'GEAR',
    white: svg.WhiteGear,
    green: svg.GreenGear,
    svgName: 'GreenGear',
    id: '41',
  },
  {
    name: 'EXTRACT',
    white: svg.WhiteExtract,
    green: svg.GreenExtract,
    svgName: 'GreenExtract',
    id: '42',
  },
  {
    name: 'EDIBLE',
    white: svg.WhiteEdible,
    green: svg.GreenEdible,
    svgName: 'GreenEdible',
    id: '43',
  },
  {
    name: 'PRE-ROLL',
    white: svg.WhitePreroll,
    green: svg.GreenPreroll,
    svgName: 'GreenPreroll',
    id: '44',
  },
  {
    name: 'TINCTURE',
    white: svg.WhiteTincture,
    green: svg.GreenTincture,
    svgName: 'GreenTincture',
    id: '45',
  },
  {
    name: 'TOPICAL',
    white: svg.WhiteTopical,
    green: svg.GreenTopical,
    svgName: 'GreenPreroll',
    id: '46',
  },
];

export const MyPassions = [
  {
    name: 'Sports',
    image: svg.Sports,
    green: svg.GreenSports,
    white: svg.WhiteSports,
    svgName: 'GreenSports',
    id: '47',
  },
  {
    name: 'Working out',
    image: svg.WorkingOut,
    green: svg.GreenWorkingOut,
    white: svg.WhiteWorkingOut,
    svgName: 'GreenWorkingOut',
    id: '48',
  },
  {
    name: 'Yoga',
    image: svg.Yoga,
    green: svg.GreenYoga,
    white: svg.WhiteYoga,
    svgName: 'GreenYoga',
    id: '49',
  },
  {
    name: 'Camping',
    image: svg.Camping,
    green: svg.GreenCamping,
    white: svg.WhiteCamping,
    svgName: 'GreenCamping',
    id: '50',
  },
  {
    name: 'Fishing',
    image: svg.Fishing,
    green: svg.GreenFishing,
    white: svg.WhiteFishing,
    svgName: 'GreenFishing',
    id: '51',
  },
  {
    name: 'Snowboarding',
    image: svg.Snowboarding,
    green: svg.GreenSnowboarding,
    white: svg.WhiteSnowboarding,
    svgName: 'GreenSnowboarding',
    id: '52',
  },
  {
    name: 'Skating',
    image: svg.Skating,
    green: svg.GreenSkating,
    white: svg.WhiteSkating,
    svgName: 'GreenSkating',
    id: '53',
  },
  {
    name: 'Skiing',
    image: svg.Skiing,
    green: svg.GreenSkiing,
    white: svg.WhiteSkiing,
    svgName: 'GreenSkiing',
    id: '54',
  },
  {
    name: 'Wine',
    image: svg.Wine,
    green: svg.GreenWine,
    white: svg.WhiteWine,
    svgName: 'GreenWine',
    id: '55',
  },
  {
    name: 'Craft Beer',
    image: svg.CraftBeer,
    green: svg.GreenCraftBeer,
    white: svg.WhiteCraftBeer,
    svgName: 'GreenCraftBeer',
    id: '56',
  },
  {
    name: 'Podcasts',
    image: svg.Podcasts,
    green: svg.GreenPodcasts,
    white: svg.WhitePodcasts,
    svgName: 'GreenPodcasts',
    id: '57',
  },
  {
    name: 'Tattoos',
    image: svg.Tattoos,
    green: svg.GreenTattoos,
    white: svg.WhiteTattoos,
    svgName: 'GreenTattoos',
    id: '58',
  },
  {
    name: 'Politics',
    image: svg.Politics,
    green: svg.GreenPolitics,
    white: svg.WhitePolitics,
    svgName: 'GreenPolitics',
    id: '59',
  },
  {
    name: 'Self care',
    image: svg.SelfCare,
    green: svg.GreenSelfCare,
    white: svg.WhiteSelfCare,
    svgName: 'GreenSelfCare',
    id: '60',
  },
  {
    name: 'Painting',
    image: svg.Painting,
    green: svg.GreenPainting,
    white: svg.WhitePainting,
    svgName: 'GreenPainting',
    id: '61',
  },
  {
    name: 'Baking',
    image: svg.Baking,
    green: svg.GreenBaking,
    white: svg.WhiteBaking,
    svgName: 'GreenBaking',
    id: '62',
  },
  {
    name: 'Surfing',
    image: svg.Surfing,
    green: svg.GreenSurfing,
    white: svg.WhiteSurfing,
    svgName: 'GreenSurfing',
    id: '63',
  },
  {
    name: 'Art',
    image: svg.Art,
    green: svg.GreenArt,
    white: svg.WhiteArt,
    svgName: 'GreenArt',
    id: '64',
  },
  {
    name: 'Music',
    image: svg.Music,
    green: svg.GreenMusic,
    white: svg.WhiteMusic,
    svgName: 'GreenMusic',
    id: '65',
  },
  {
    name: 'Clubbing',
    image: svg.Clubbing,
    green: svg.GreenClubbing,
    white: svg.WhiteClubbing,
    svgName: 'GreenClubbing',
    id: '66',
  },
  {
    name: 'Dance',
    image: svg.Dance,
    green: svg.GreenDance,
    white: svg.WhiteDance,
    svgName: 'GreenDance',
    id: '67',
  },
  {
    name: 'Reading',
    image: svg.Reading,
    green: svg.GreenReading,
    white: svg.WhiteReading,
    svgName: 'GreenReading',
    id: '68',
  },
  {
    name: 'Learning',
    image: svg.Learning,
    green: svg.GreenLearning,
    white: svg.WhiteLearning,
    svgName: 'GreenLearning',

    id: '69',
  },
  {
    name: 'Cooking',
    image: svg.Cooking,
    green: svg.GreenCooking,
    white: svg.WhiteCooking,
    svgName: 'GreenCooking',
    id: '70',
  },
  {
    name: 'Movie Nights',
    image: svg.MovieNights,
    green: svg.GreenMovieNights,
    white: svg.WhiteMovieNights,
    svgName: 'GreenMovieNights',
    id: '71',
  },
  {
    name: 'Comedy',
    image: svg.Comedy,
    green: svg.GreenComedy,
    white: svg.WhiteComedy,
    svgName: 'GreenComedy',
    id: '72',
  },
  {
    name: 'Gardening',
    image: svg.Gardening,
    green: svg.GreenGardening,
    white: svg.WhiteGardening,
    svgName: 'GreenGardening',
    id: '73',
  },
  {
    name: 'Blogging',
    image: svg.Blogging,
    green: svg.GreenBlogging,
    white: svg.WhiteBlogging,
    svgName: 'GreenBlogging',
    id: '74',
  },
  {
    name: 'Traveling',
    image: svg.Traveling,
    green: svg.GreenTraveling,
    white: svg.WhiteTraveling,
    svgName: 'GreenTraveling',
    id: '75',
  },
  {
    name: 'Entrepreneurship',
    image: svg.Entrepreneurship,
    green: svg.GreenEntrepreneurship,
    white: svg.WhiteEntrepreneurship,
    svgName: 'GreenEntrepreneurship',
    id: '76',
  },
  {
    name: 'Fashion',
    image: svg.Fashion,
    green: svg.GreenFashion,
    white: svg.WhiteFashion,
    svgName: 'GreenFashion',
    id: '77',
  },
  {
    name: 'Photography',
    image: svg.Photography,
    green: svg.GreenPhotography,
    white: svg.WhitePhotography,
    svgName: 'GreenPhotography',
    id: '78',
  },
  {
    name: 'Environmentalism',
    image: svg.Environmentalism,
    green: svg.GreenEnvironmentalism,
    white: svg.WhiteEnvironmentalism,
    svgName: 'GreenEnvironmentalism',
    id: '79',
  },
  {
    name: 'Video Games',
    image: svg.VideoGames,
    green: svg.GreenVideoGames,
    white: svg.WhiteVideoGames,
    svgName: 'GreenVideoGames',
    id: '80',
  },
  {
    name: 'Astrology',
    image: svg.Astrology,
    green: svg.GreenAstrology,
    white: svg.WhiteAstrology,
    svgName: 'GreenAstrology',
    id: '81',
  },
  {
    name: 'Sex',
    image: svg.Sex,
    green: svg.GreenSex,
    white: svg.WhiteSex,
    svgName: 'GreenSex',
    id: '82',
  },
  {
    name: 'Shopping',
    image: svg.Shopping,
    green: svg.GreenShopping,
    white: svg.WhiteShopping,
    svgName: 'GreenShopping',
    id: '83',
  },
];
