export const data = [
  '2 girls 1 cup',
  '2g1c',
  'assfuck',
  'assfucker',
  'ass-fucker',
  'assfukka',
  'assgoblin',
  'asshopper',
  'ass-jabber',
  'assjacker',
  'asslick',
  'asslicker',
  'assmonkey',
  'assmunch',
  'assmuncher',
  'assnigger',
  'asspirate',
  'ass-pirate',
  'beaner',
  'beaners',
  'beastial',
  'beastiality',
  'bestial',
  'bestiality',
  'bi+ch',
  'biatch',
  'bimbos',
  'bitch',
  'bitchass',
  'bitcher',
  'bitchers',
  'bitches',
  'bitchin',
  'bitching',
  'bitchtits',
  'bitchy',
  'boiolas',
  'brotherfucker',
  'brown showers',
  'bulldyke',
  'camslut',
  'camwhore',
  'carpet muncher',
  'carpetmuncher',
  'chinc',
  'chink',
  'choad',
  'chode',
  'clitface',
  'clitfuck',
  'cnut',
  'cockfucker',
  'cockjockey',
  'cockknoker',
  'cockmaster',
  'cockmongler',
  'cockmongruel',
  'cockmonkey',
  'cockmunch',
  'cockmuncher',
  'cocksmoke',
  'cocksmoker',
  'cocksniffer',
  'cocksuck',
  'cocksucked',
  'cocksucker',
  'cock-sucker',
  'cocksucking',
  'cocksucks',
  'cocksuka',
  'cocksukka',
  'cockwaffle',
  'cok',
  'cokmuncher',
  'coksucka',
  'coon',
  'coons',
  'cooter',
  'cumdumpster',
  'cumguzzler',
  'cumjockey',
  'cumslut',
  'cumtart',
  'cunt',
  'cuntass',
  'cuntface',
  'cunthole',
  'cuntlick',
  'cuntlicker',
  'cuntlicking',
  'cuntrag',
  'cunts',
  'cuntslut',
  'cyalis',
  'cyberfuc',
  'cyberfuck',
  'cyberfucked',
  'cyberfucker',
  'cyberfuckers',
  'cyberfucking',
  'dago',
  'darkie',
  'date rape',
  'daterape',
  'deggo',
  'dickfuck',
  'dickfucker',
  'dickmonger',
  'dicksucker',
  'dicksucking',
  'dicktickler',
  'dirsa',
  'dog-fucker',
  'dolcett',
  'donkey punch',
  'douche-fag',
  'dumbcunt',
  'dyke',
  'eat my ass',
  'escort',
  'fag',
  'fagbag',
  'fagfucker',
  'fagging',
  'faggit',
  'faggitt',
  'faggot',
  'faggotcock',
  'faggs',
  'fagot',
  'fagots',
  'fags',
  'fagtard',
  'figging',
  'fistfuck',
  'fistfucked',
  'fistfucker',
  'fistfuckers',
  'fistfucking',
  'fistfuckings',
  'fistfucks',
  'fisting',
  'flamer',
  'fucka',
  'fuckass',
  'fuckbag',
  'fuckboy',
  'fuckbrain',
  'fuckbutt',
  'fuckbutter',
  'fucktard',
  'fucktards',
  'fucktart',
  'fudge packer',
  'fudgepacker',
  'gayass',
  'gaybob',
  'gaydo',
  'gayfuck',
  'gayfuckist',
  'gaylord',
  'gaytard',
  'gaywad',
  'goatcx',
  'goatse',
  'gokkun',
  'goo girl',
  'gooch',
  'gook',
  'goregasm',
  'gringo',
  'grope',
  'guro',
  'heeb',
  'heshe',
  'ho',
  'hoar',
  'hoare',
  'hoe',
  'hoer',
  'homo',
  'homodumbshit',
  'honkey',
  'hooker',
  'hore',
  'hot carl',
  'how to kill',
  'how to murder',
  'incest',
  'jail bait',
  'jailbait',
  'jap',
  'jigaboo',
  'jiggaboo',
  'jiggerboo',
  'jungle bunny',
  'junglebunny',
  'kike',
  'knobjocky',
  'knobjokey',
  'kooch',
  'kootch',
  'kraut',
  'kunt',
  'kyke',
  'l3i+ch',
  'l3itch',
  'lemon party',
  'lesbo',
  'lezzie',
  'm0f0',
  'mcfagget',
  'milf',
  'minge',
  'missionary position',
  'mof0',
  'mofo',
  'mo-fo',
  'mothafuck',
  'mothafucka',
  'mothafuckas',
  'mothafuckaz',
  'mothafucked',
  'mothafucker',
  'mothafuckers',
  'mothafuckin',
  'mothafucking',
  'mothafuckings',
  'mothafucks',
  'mother fucker',
  'motherfuck',
  'motherfucked',
  'motherfucker',
  'motherfuckers',
  'motherfuckin',
  'motherfucking',
  'motherfuckings',
  'motherfuckka',
  'motherfucks',
  'muff diver',
  'muffdiver',
  'muffdiving',
  'munging',
  'mutha',
  'muthafecker',
  'muthafuckker',
  'muther',
  'mutherfucker',
  'n1gga',
  'n1gger',
  'nambla',
  'nazi',
  'negro',
  'neonazi',
  'nig nog',
  'nigaboo',
  'nigg3r',
  'nigg4h',
  'nigga',
  'niggah',
  'niggas',
  'niggaz',
  'nigger',
  'niggers',
  'niglet',
  'nob jokey',
  'nobjocky',
  'nobjokey',
  'nsfw images',
  'omorashi',
  'one cup two girls',
  'one guy one jar',
  'p0rn',
  'paedophile',
  'panooch',
  'pedobear',
  'pedophile',
  'penisbanger',
  'penisfucker',
  'penispuffer',
  'phone sex',
  'phonesex',
  'piece of shit',
  'pigfucker',
  'piss pig',
  'pisspig',
  'pole smoker',
  'polesmoker',
  'pollock',
  'poopuncher',
  'porch monkey',
  'porchmonkey',
  'pron',
  'pthc',
  'punanny',
  'punany',
  'punta',
  'pusse',
  'pussi',
  'pussies',
  'pussy',
  'pussylicking',
  'pussys',
  'pust',
  'puto',
  'queerbait',
  'queerhole',
  'quim',
  'raghead',
  'rape',
  'raping',
  'rapist',
  'retard',
  'ruski',
  's.o.b.',
  'sadist',
  'sand nigger',
  'sandnigger',
  'santorum',
  'scat',
  'shemale',
  'shitcunt',
  'shitdick',
  'skank',
  'skeet',
  'skullfuck',
  'slag',
  'slanteye',
  'slut',
  'slutbag',
  'sluts',
  'smeg',
  'smegma',
  'smut',
  'snatch',
  'snowballing',
  'sodomize',
  'sodomy',
  'son-of-a-bitch',
  'spac',
  'spic',
  'spick',
  'spooge',
  'suckass',
  'suicide girls',
  'tard',
  'thundercunt',
  'tied up',
  'towelhead',
  'tranny',
  'tub girl',
  'tubgirl',
  'tw4t',
  'twat',
  'twathead',
  'twatlips',
  'twats',
  'twatty',
  'twatwaffle',
  'two girls one cup',
  'upskirt',
  'v14gra',
  'v1gra',
  'viagra',
  'vorarephilia',
  'voyeur',
  'w00se',
  'wetback',
  'white power',
  'whoar',
  'whore',
  'whorebag',
  'whoreface',
  'wop',
  'wrapping men',
  'wrinkled starfish',
  'zoophilia',
  'zubb',
  'arian',
  'aryan',
  'assbang',
  'assbanged',
  'assbangs',
  'assfuck',
  'assfucker',
  'assmaster',
  'assmunch',
  'b1tch',
  'bastard',
  'bastards',
  'bawdy',
  'beastiality',
  'beatch',
  'beater',
  'beeyotch',
  'beotch',
  'biatch',
  'bimbo',
  'bitch',
  'bitched',
  'bitches',
  'buttfucker',
  'carpetmuncher',
  'chinc',
  'chincs',
  'chink',
  'cock sucker',
  'cocksmoker',
  'cocksucker',
  'commie',
  'coon',
  'coons',
  'corksucker',
  'cracker',
  'crackwhore',
  'cumslut',
  'cunt',
  'c-u-n-t',
  'cuntface',
  'cunthunter',
  'cuntlick',
  'cuntlicker',
  'cunts',
  'dike',
  'dyke',
  'dykes',
  'essohbee',
  'extacy',
  'extasy',
  'fag',
  'fagg',
  'fagged',
  'faggit',
  'faggot',
  'fagot',
  'fags',
  'faig',
  'faigt',
  'felch',
  'felcher',
  'felching',
  'fellate',
  'fellatio',
  'feltch',
  'feltcher',
  'fisted',
  'fisting',
  'fisty',
  'floozy',
  'foad',
  'fondle',
  'fucktard',
  'fuck-tard',
  'fudgepacker',
  'gooks',
  'gringo',
  'guido',
  'h0m0',
  'h0mo',
  'heroin',
  'hobag',
  'hom0',
  'homo',
  'homoey',
  'honky',
  'hooker',
  'hussy',
  'inbred',
  'incest',
  'injun',
  'jap',
  'japs',
  'junkie',
  'junky',
  'kike',
  'kikes',
  'kill',
  'kkk',
  'klan',
  'kraut',
  'kyke',
  'meth',
  'm-fucking',
  'mofo',
  'molest',
  'moolie',
  'moron',
  'motherfucka',
  'motherfucker',
  'motherfucking',
  'mtherfucker',
  'mthrfucker',
  'mthrfucking',
  'muffdiver',
  'murder',
  'muthafuckaz',
  'muthafucker',
  'mutherfucker',
  'mutherfucking',
  'muthrfucking',
  'napalm',
  'nazi',
  'nazism',
  'negro',
  'nigga',
  'niggah',
  'niggas',
  'niggaz',
  'nigger',
  'niggers',
  'niggle',
  'niglet',
  'paddy',
  'polack',
  'pollock',
  'puto',
  'queaf',
  'queef',
  'queer',
  'queero',
  'queers',
  'rape',
  'raped',
  'raper',
  'reetard',
  'rumprammer',
  'ruski',
  'scag',
  'slut',
  'slutdumper',
  'slutkiss',
  'sluts',
  'spic',
  'spick',
  'spik',
  'spiks',
  'sumofabiatch',
  'tard',
  'tubgirl',
  'twat',
  'twats',
  'uzi',
  'wedgie',
  'wetback',
  'whitey',
  'wop',
];

export const dataSet2 = [
  201,
  'two*zero*one',
  'two-zero-one',
  'two zero one',
  202,
  'two*zero*two',
  'two-zero-two',
  'two zero two',
  203,
  'two*zero*three',
  'two-zero-three',
  'two zero three',
  204,
  'two*zero*four',
  'two-zero-four',
  'two zero four',
  205,
  'two*zero*five',
  'two-zero-five',
  'two zero five',
  206,
  'two*zero*six',
  'two-zero-six',
  'two zero six',
  207,
  'two*zero*seven',
  'two-zero-seven',
  'two zero seven',
  208,
  'two*zero*eight',
  'two-zero-eight',
  'two zero eight',
  209,
  'two*zero*nine',
  'two-zero-nine',
  'two zero nine',
  210,
  'two*one*zero',
  'two-one-zero',
  'two one zero',
  212,
  'two*one*two',
  'two-one-two',
  'two one two',
  213,
  'two*one*three',
  'two-one-three',
  'two one three',
  214,
  'two*one*four',
  'two-one-four',
  'two one four',
  215,
  'two*one*five',
  'two-one-five',
  'two one five',
  216,
  'two*one*six',
  'two-one-six',
  'two one six',
  217,
  'two*one*seven',
  'two-one-seven',
  'two one seven',
  218,
  'two*one*eight',
  'two-one-eight',
  'two one eight',
  219,
  'two*one*nine',
  'two-one-nine',
  'two one nine',
  220,
  'two*two*zero',
  'two-two-zero',
  'two two zero',
  223,
  'two*two*three',
  'two-two-three',
  'two two three',
  224,
  'two*two*four',
  'two-two-four',
  'two two four',
  225,
  'two*two*five',
  'two-two-five',
  'two two five',
  226,
  'two*two*six',
  'two-two-six',
  'two two six',
  228,
  'two*two*eight',
  'two-two-eight',
  'two two eight',
  229,
  'two*two*nine',
  'two-two-nine',
  'two two nine',
  231,
  'two*three*one',
  'two-three-one',
  'two three one',
  234,
  'two*three*four',
  'two-three-four',
  'two three four',
  236,
  'two*three*six',
  'two-three-six',
  'two three six',
  239,
  'two*three*nine',
  'two-three-nine',
  'two three nine',
  240,
  'two*four*zero',
  'two-four-zero',
  'two four zero',
  242,
  'two*four*two',
  'two-four-two',
  'two four two',
  246,
  'two*four*six',
  'two-four-six',
  'two four six',
  248,
  'two*four*eight',
  'two-four-eight',
  'two four eight',
  249,
  'two*four*nine',
  'two-four-nine',
  'two four nine',
  250,
  'two*five*zero',
  'two-five-zero',
  'two five zero',
  251,
  'two*five*one',
  'two-five-one',
  'two five one',
  252,
  'two*five*two',
  'two-five-two',
  'two five two',
  253,
  'two*five*three',
  'two-five-three',
  'two five three',
  254,
  'two*five*four',
  'two-five-four',
  'two five four',
  256,
  'two*five*six',
  'two-five-six',
  'two five six',
  260,
  'two*six*zero',
  'two-six-zero',
  'two six zero',
  262,
  'two*six*two',
  'two-six-two',
  'two six two',
  264,
  'two*six*four',
  'two-six-four',
  'two six four',
  267,
  'two*six*seven',
  'two-six-seven',
  'two six seven',
  268,
  'two*six*eight',
  'two-six-eight',
  'two six eight',
  269,
  'two*six*nine',
  'two-six-nine',
  'two six nine',
  270,
  'two*seven*zero',
  'two-seven-zero',
  'two seven zero',
  272,
  'two*seven*two',
  'two-seven-two',
  'two seven two',
  276,
  'two*seven*six',
  'two-seven-six',
  'two seven six',
  279,
  'two*seven*nine',
  'two-seven-nine',
  'two seven nine',
  281,
  'two*eight*one',
  'two-eight-one',
  'two eight one',
  284,
  'two*eight*four',
  'two-eight-four',
  'two eight four',
  289,
  'two*eight*nine',
  'two-eight-nine',
  'two eight nine',
  301,
  'three*zero*one',
  'three-zero-one',
  'three zero one',
  302,
  'three*zero*two',
  'three-zero-two',
  'three zero two',
  303,
  'three*zero*three',
  'three-zero-three',
  'three zero three',
  304,
  'three*zero*four',
  'three-zero-four',
  'three zero four',
  305,
  'three*zero*five',
  'three-zero-five',
  'three zero five',
  306,
  'three*zero*six',
  'three-zero-six',
  'three zero six',
  307,
  'three*zero*seven',
  'three-zero-seven',
  'three zero seven',
  308,
  'three*zero*eight',
  'three-zero-eight',
  'three zero eight',
  309,
  'three*zero*nine',
  'three-zero-nine',
  'three zero nine',
  310,
  'three*one*zero',
  'three-one-zero',
  'three one zero',
  312,
  'three*one*two',
  'three-one-two',
  'three one two',
  313,
  'three*one*three',
  'three-one-three',
  'three one three',
  314,
  'three*one*four',
  'three-one-four',
  'three one four',
  315,
  'three*one*five',
  'three-one-five',
  'three one five',
  316,
  'three*one*six',
  'three-one-six',
  'three one six',
  317,
  'three*one*seven',
  'three-one-seven',
  'three one seven',
  318,
  'three*one*eight',
  'three-one-eight',
  'three one eight',
  319,
  'three*one*nine',
  'three-one-nine',
  'three one nine',
  320,
  'three*two*zero',
  'three-two-zero',
  'three two zero',
  321,
  'three*two*one',
  'three-two-one',
  'three two one',
  323,
  'three*two*three',
  'three-two-three',
  'three two three',
  325,
  'three*two*five',
  'three-two-five',
  'three two five',
  326,
  'three*two*six',
  'three-two-six',
  'three two six',
  330,
  'three*three*zero',
  'three-three-zero',
  'three three zero',
  331,
  'three*three*one',
  'three-three-one',
  'three three one',
  332,
  'three*three*two',
  'three-three-two',
  'three three two',
  334,
  'three*three*four',
  'three-three-four',
  'three three four',
  336,
  'three*three*six',
  'three-three-six',
  'three three six',
  337,
  'three*three*seven',
  'three-three-seven',
  'three three seven',
  339,
  'three*three*nine',
  'three-three-nine',
  'three three nine',
  340,
  'three*four*zero',
  'three-four-zero',
  'three four zero',
  341,
  'three*four*one',
  'three-four-one',
  'three four one',
  343,
  'three*four*three',
  'three-four-three',
  'three four three',
  345,
  'three*four*five',
  'three-four-five',
  'three four five',
  346,
  'three*four*six',
  'three-four-six',
  'three four six',
  347,
  'three*four*seven',
  'three-four-seven',
  'three four seven',
  351,
  'three*five*one',
  'three-five-one',
  'three five one',
  352,
  'three*five*two',
  'three-five-two',
  'three five two',
  360,
  'three*six*zero',
  'three-six-zero',
  'three six zero',
  361,
  'three*six*one',
  'three-six-one',
  'three six one',
  364,
  'three*six*four',
  'three-six-four',
  'three six four',
  365,
  'three*six*five',
  'three-six-five',
  'three six five',
  367,
  'three*six*seven',
  'three-six-seven',
  'three six seven',
  368,
  'three*six*eight',
  'three-six-eight',
  'three six eight',
  380,
  'three*eight*zero',
  'three-eight-zero',
  'three eight zero',
  385,
  'three*eight*five',
  'three-eight-five',
  'three eight five',
  386,
  'three*eight*six',
  'three-eight-six',
  'three eight six',
  401,
  'four*zero*one',
  'four-zero-one',
  'four zero one',
  402,
  'four*zero*two',
  'four-zero-two',
  'four zero two',
  403,
  'four*zero*three',
  'four-zero-three',
  'four zero three',
  404,
  'four*zero*four',
  'four-zero-four',
  'four zero four',
  405,
  'four*zero*five',
  'four-zero-five',
  'four zero five',
  406,
  'four*zero*six',
  'four-zero-six',
  'four zero six',
  407,
  'four*zero*seven',
  'four-zero-seven',
  'four zero seven',
  408,
  'four*zero*eight',
  'four-zero-eight',
  'four zero eight',
  409,
  'four*zero*nine',
  'four-zero-nine',
  'four zero nine',
  410,
  'four*one*zero',
  'four-one-zero',
  'four one zero',
  412,
  'four*one*two',
  'four-one-two',
  'four one two',
  413,
  'four*one*three',
  'four-one-three',
  'four one three',
  414,
  'four*one*four',
  'four-one-four',
  'four one four',
  415,
  'four*one*five',
  'four-one-five',
  'four one five',
  416,
  'four*one*six',
  'four-one-six',
  'four one six',
  417,
  'four*one*seven',
  'four-one-seven',
  'four one seven',
  418,
  'four*one*eight',
  'four-one-eight',
  'four one eight',
  419,
  'four*one*nine',
  'four-one-nine',
  'four one nine',
  423,
  'four*two*three',
  'four-two-three',
  'four two three',
  424,
  'four*two*four',
  'four-two-four',
  'four two four',
  425,
  'four*two*five',
  'four-two-five',
  'four two five',
  430,
  'four*three*zero',
  'four-three-zero',
  'four three zero',
  431,
  'four*three*one',
  'four-three-one',
  'four three one',
  432,
  'four*three*two',
  'four-three-two',
  'four three two',
  434,
  'four*three*four',
  'four-three-four',
  'four three four',
  435,
  'four*three*five',
  'four-three-five',
  'four three five',
  437,
  'four*three*seven',
  'four-three-seven',
  'four three seven',
  438,
  'four*three*eight',
  'four-three-eight',
  'four three eight',
  440,
  'four*four*zero',
  'four-four-zero',
  'four four zero',
  441,
  'four*four*one',
  'four-four-one',
  'four four one',
  442,
  'four*four*two',
  'four-four-two',
  'four four two',
  443,
  'four*four*three',
  'four-four-three',
  'four four three',
  445,
  'four*four*five',
  'four-four-five',
  'four four five',
  447,
  'four*four*seven',
  'four-four-seven',
  'four four seven',
  448,
  'four*four*eight',
  'four-four-eight',
  'four four eight',
  450,
  'four*five*zero',
  'four-five-zero',
  'four five zero',
  458,
  'four*five*eight',
  'four-five-eight',
  'four five eight',
  463,
  'four*six*three',
  'four-six-three',
  'four six three',
  464,
  'four*six*four',
  'four-six-four',
  'four six four',
  469,
  'four*six*nine',
  'four-six-nine',
  'four six nine',
  470,
  'four*seven*zero',
  'four-seven-zero',
  'four seven zero',
  473,
  'four*seven*three',
  'four-seven-three',
  'four seven three',
  474,
  'four*seven*four',
  'four-seven-four',
  'four seven four',
  475,
  'four*seven*five',
  'four-seven-five',
  'four seven five',
  478,
  'four*seven*eight',
  'four-seven-eight',
  'four seven eight',
  479,
  'four*seven*nine',
  'four-seven-nine',
  'four seven nine',
  480,
  'four*eight*zero',
  'four-eight-zero',
  'four eight zero',
  484,
  'four*eight*four',
  'four-eight-four',
  'four eight four',
  501,
  'five*zero*one',
  'five-zero-one',
  'five zero one',
  502,
  'five*zero*two',
  'five-zero-two',
  'five zero two',
  503,
  'five*zero*three',
  'five-zero-three',
  'five zero three',
  504,
  'five*zero*four',
  'five-zero-four',
  'five zero four',
  505,
  'five*zero*five',
  'five-zero-five',
  'five zero five',
  506,
  'five*zero*six',
  'five-zero-six',
  'five zero six',
  507,
  'five*zero*seven',
  'five-zero-seven',
  'five zero seven',
  508,
  'five*zero*eight',
  'five-zero-eight',
  'five zero eight',
  509,
  'five*zero*nine',
  'five-zero-nine',
  'five zero nine',
  510,
  'five*one*zero',
  'five-one-zero',
  'five one zero',
  512,
  'five*one*two',
  'five-one-two',
  'five one two',
  513,
  'five*one*three',
  'five-one-three',
  'five one three',
  514,
  'five*one*four',
  'five-one-four',
  'five one four',
  515,
  'five*one*five',
  'five-one-five',
  'five one five',
  516,
  'five*one*six',
  'five-one-six',
  'five one six',
  517,
  'five*one*seven',
  'five-one-seven',
  'five one seven',
  518,
  'five*one*eight',
  'five-one-eight',
  'five one eight',
  519,
  'five*one*nine',
  'five-one-nine',
  'five one nine',
  520,
  'five*two*zero',
  'five-two-zero',
  'five two zero',
  530,
  'five*three*zero',
  'five-three-zero',
  'five three zero',
  531,
  'five*three*one',
  'five-three-one',
  'five three one',
  534,
  'five*three*four',
  'five-three-four',
  'five three four',
  539,
  'five*three*nine',
  'five-three-nine',
  'five three nine',
  540,
  'five*four*zero',
  'five-four-zero',
  'five four zero',
  541,
  'five*four*one',
  'five-four-one',
  'five four one',
  548,
  'five*four*eight',
  'five-four-eight',
  'five four eight',
  551,
  'five*five*one',
  'five-five-one',
  'five five one',
  559,
  'five*five*nine',
  'five-five-nine',
  'five five nine',
  561,
  'five*six*one',
  'five-six-one',
  'five six one',
  562,
  'five*six*two',
  'five-six-two',
  'five six two',
  563,
  'five*six*three',
  'five-six-three',
  'five six three',
  564,
  'five*six*four',
  'five-six-four',
  'five six four',
  567,
  'five*six*seven',
  'five-six-seven',
  'five six seven',
  570,
  'five*seven*zero',
  'five-seven-zero',
  'five seven zero',
  571,
  'five*seven*one',
  'five-seven-one',
  'five seven one',
  572,
  'five*seven*two',
  'five-seven-two',
  'five seven two',
  573,
  'five*seven*three',
  'five-seven-three',
  'five seven three',
  574,
  'five*seven*four',
  'five-seven-four',
  'five seven four',
  575,
  'five*seven*five',
  'five-seven-five',
  'five seven five',
  579,
  'five*seven*nine',
  'five-seven-nine',
  'five seven nine',
  580,
  'five*eight*zero',
  'five-eight-zero',
  'five eight zero',
  581,
  'five*eight*one',
  'five-eight-one',
  'five eight one',
  582,
  'five*eight*two',
  'five-eight-two',
  'five eight two',
  585,
  'five*eight*five',
  'five-eight-five',
  'five eight five',
  586,
  'five*eight*six',
  'five-eight-six',
  'five eight six',
  587,
  'five*eight*seven',
  'five-eight-seven',
  'five eight seven',
  601,
  'six*zero*one',
  'six-zero-one',
  'six zero one',
  602,
  'six*zero*two',
  'six-zero-two',
  'six zero two',
  603,
  'six*zero*three',
  'six-zero-three',
  'six zero three',
  604,
  'six*zero*four',
  'six-zero-four',
  'six zero four',
  605,
  'six*zero*five',
  'six-zero-five',
  'six zero five',
  606,
  'six*zero*six',
  'six-zero-six',
  'six zero six',
  607,
  'six*zero*seven',
  'six-zero-seven',
  'six zero seven',
  608,
  'six*zero*eight',
  'six-zero-eight',
  'six zero eight',
  609,
  'six*zero*nine',
  'six-zero-nine',
  'six zero nine',
  610,
  'six*one*zero',
  'six-one-zero',
  'six one zero',
  612,
  'six*one*two',
  'six-one-two',
  'six one two',
  613,
  'six*one*three',
  'six-one-three',
  'six one three',
  614,
  'six*one*four',
  'six-one-four',
  'six one four',
  615,
  'six*one*five',
  'six-one-five',
  'six one five',
  616,
  'six*one*six',
  'six-one-six',
  'six one six',
  617,
  'six*one*seven',
  'six-one-seven',
  'six one seven',
  618,
  'six*one*eight',
  'six-one-eight',
  'six one eight',
  619,
  'six*one*nine',
  'six-one-nine',
  'six one nine',
  620,
  'six*two*zero',
  'six-two-zero',
  'six two zero',
  623,
  'six*two*three',
  'six-two-three',
  'six two three',
  626,
  'six*two*six',
  'six-two-six',
  'six two six',
  628,
  'six*two*eight',
  'six-two-eight',
  'six two eight',
  629,
  'six*two*nine',
  'six-two-nine',
  'six two nine',
  630,
  'six*three*zero',
  'six-three-zero',
  'six three zero',
  631,
  'six*three*one',
  'six-three-one',
  'six three one',
  636,
  'six*three*six',
  'six-three-six',
  'six three six',
  639,
  'six*three*nine',
  'six-three-nine',
  'six three nine',
  640,
  'six*four*zero',
  'six-four-zero',
  'six four zero',
  641,
  'six*four*one',
  'six-four-one',
  'six four one',
  646,
  'six*four*six',
  'six-four-six',
  'six four six',
  647,
  'six*four*seven',
  'six-four-seven',
  'six four seven',
  649,
  'six*four*nine',
  'six-four-nine',
  'six four nine',
  650,
  'six*five*zero',
  'six-five-zero',
  'six five zero',
  651,
  'six*five*one',
  'six-five-one',
  'six five one',
  656,
  'six*five*six',
  'six-five-six',
  'six five six',
  657,
  'six*five*seven',
  'six-five-seven',
  'six five seven',
  658,
  'six*five*eight',
  'six-five-eight',
  'six five eight',
  659,
  'six*five*nine',
  'six-five-nine',
  'six five nine',
  660,
  'six*six*zero',
  'six-six-zero',
  'six six zero',
  661,
  'six*six*one',
  'six-six-one',
  'six six one',
  662,
  'six*six*two',
  'six-six-two',
  'six six two',
  664,
  'six*six*four',
  'six-six-four',
  'six six four',
  667,
  'six*six*seven',
  'six-six-seven',
  'six six seven',
  669,
  'six*six*nine',
  'six-six-nine',
  'six six nine',
  670,
  'six*seven*zero',
  'six-seven-zero',
  'six seven zero',
  671,
  'six*seven*one',
  'six-seven-one',
  'six seven one',
  672,
  'six*seven*two',
  'six-seven-two',
  'six seven two',
  678,
  'six*seven*eight',
  'six-seven-eight',
  'six seven eight',
  680,
  'six*eight*zero',
  'six-eight-zero',
  'six eight zero',
  681,
  'six*eight*one',
  'six-eight-one',
  'six eight one',
  682,
  'six*eight*two',
  'six-eight-two',
  'six eight two',
  683,
  'six*eight*three',
  'six-eight-three',
  'six eight three',
  684,
  'six*eight*four',
  'six-eight-four',
  'six eight four',
  689,
  'six*eight*nine',
  'six-eight-nine',
  'six eight nine',
  701,
  'seven*zero*one',
  'seven-zero-one',
  'seven zero one',
  702,
  'seven*zero*two',
  'seven-zero-two',
  'seven zero two',
  703,
  'seven*zero*three',
  'seven-zero-three',
  'seven zero three',
  704,
  'seven*zero*four',
  'seven-zero-four',
  'seven zero four',
  705,
  'seven*zero*five',
  'seven-zero-five',
  'seven zero five',
  706,
  'seven*zero*six',
  'seven-zero-six',
  'seven zero six',
  707,
  'seven*zero*seven',
  'seven-zero-seven',
  'seven zero seven',
  708,
  'seven*zero*eight',
  'seven-zero-eight',
  'seven zero eight',
  709,
  'seven*zero*nine',
  'seven-zero-nine',
  'seven zero nine',
  712,
  'seven*one*two',
  'seven-one-two',
  'seven one two',
  713,
  'seven*one*three',
  'seven-one-three',
  'seven one three',
  714,
  'seven*one*four',
  'seven-one-four',
  'seven one four',
  715,
  'seven*one*five',
  'seven-one-five',
  'seven one five',
  716,
  'seven*one*six',
  'seven-one-six',
  'seven one six',
  717,
  'seven*one*seven',
  'seven-one-seven',
  'seven one seven',
  718,
  'seven*one*eight',
  'seven-one-eight',
  'seven one eight',
  719,
  'seven*one*nine',
  'seven-one-nine',
  'seven one nine',
  720,
  'seven*two*zero',
  'seven-two-zero',
  'seven two zero',
  721,
  'seven*two*one',
  'seven-two-one',
  'seven two one',
  724,
  'seven*two*four',
  'seven-two-four',
  'seven two four',
  725,
  'seven*two*five',
  'seven-two-five',
  'seven two five',
  726,
  'seven*two*six',
  'seven-two-six',
  'seven two six',
  727,
  'seven*two*seven',
  'seven-two-seven',
  'seven two seven',
  731,
  'seven*three*one',
  'seven-three-one',
  'seven three one',
  732,
  'seven*three*two',
  'seven-three-two',
  'seven three two',
  734,
  'seven*three*four',
  'seven-three-four',
  'seven three four',
  737,
  'seven*three*seven',
  'seven-three-seven',
  'seven three seven',
  740,
  'seven*four*zero',
  'seven-four-zero',
  'seven four zero',
  742,
  'seven*four*two',
  'seven-four-two',
  'seven four two',
  743,
  'seven*four*three',
  'seven-four-three',
  'seven four three',
  747,
  'seven*four*seven',
  'seven-four-seven',
  'seven four seven',
  753,
  'seven*five*three',
  'seven-five-three',
  'seven five three',
  754,
  'seven*five*four',
  'seven-five-four',
  'seven five four',
  757,
  'seven*five*seven',
  'seven-five-seven',
  'seven five seven',
  758,
  'seven*five*eight',
  'seven-five-eight',
  'seven five eight',
  760,
  'seven*six*zero',
  'seven-six-zero',
  'seven six zero',
  762,
  'seven*six*two',
  'seven-six-two',
  'seven six two',
  763,
  'seven*six*three',
  'seven-six-three',
  'seven six three',
  765,
  'seven*six*five',
  'seven-six-five',
  'seven six five',
  767,
  'seven*six*seven',
  'seven-six-seven',
  'seven six seven',
  769,
  'seven*six*nine',
  'seven-six-nine',
  'seven six nine',
  770,
  'seven*seven*zero',
  'seven-seven-zero',
  'seven seven zero',
  771,
  'seven*seven*one',
  'seven-seven-one',
  'seven seven one',
  772,
  'seven*seven*two',
  'seven-seven-two',
  'seven seven two',
  773,
  'seven*seven*three',
  'seven-seven-three',
  'seven seven three',
  774,
  'seven*seven*four',
  'seven-seven-four',
  'seven seven four',
  775,
  'seven*seven*five',
  'seven-seven-five',
  'seven seven five',
  778,
  'seven*seven*eight',
  'seven-seven-eight',
  'seven seven eight',
  779,
  'seven*seven*nine',
  'seven-seven-nine',
  'seven seven nine',
  780,
  'seven*eight*zero',
  'seven-eight-zero',
  'seven eight zero',
  781,
  'seven*eight*one',
  'seven-eight-one',
  'seven eight one',
  782,
  'seven*eight*two',
  'seven-eight-two',
  'seven eight two',
  784,
  'seven*eight*four',
  'seven-eight-four',
  'seven eight four',
  785,
  'seven*eight*five',
  'seven-eight-five',
  'seven eight five',
  786,
  'seven*eight*six',
  'seven-eight-six',
  'seven eight six',
  787,
  'seven*eight*seven',
  'seven-eight-seven',
  'seven eight seven',
  801,
  'eight*zero*one',
  'eight-zero-one',
  'eight zero one',
  802,
  'eight*zero*two',
  'eight-zero-two',
  'eight zero two',
  803,
  'eight*zero*three',
  'eight-zero-three',
  'eight zero three',
  804,
  'eight*zero*four',
  'eight-zero-four',
  'eight zero four',
  805,
  'eight*zero*five',
  'eight-zero-five',
  'eight zero five',
  806,
  'eight*zero*six',
  'eight-zero-six',
  'eight zero six',
  807,
  'eight*zero*seven',
  'eight-zero-seven',
  'eight zero seven',
  808,
  'eight*zero*eight',
  'eight-zero-eight',
  'eight zero eight',
  809,
  'eight*zero*nine',
  'eight-zero-nine',
  'eight zero nine',
  810,
  'eight*one*zero',
  'eight-one-zero',
  'eight one zero',
  812,
  'eight*one*two',
  'eight-one-two',
  'eight one two',
  813,
  'eight*one*three',
  'eight-one-three',
  'eight one three',
  814,
  'eight*one*four',
  'eight-one-four',
  'eight one four',
  815,
  'eight*one*five',
  'eight-one-five',
  'eight one five',
  816,
  'eight*one*six',
  'eight-one-six',
  'eight one six',
  817,
  'eight*one*seven',
  'eight-one-seven',
  'eight one seven',
  818,
  'eight*one*eight',
  'eight-one-eight',
  'eight one eight',
  819,
  'eight*one*nine',
  'eight-one-nine',
  'eight one nine',
  820,
  'eight*two*zero',
  'eight-two-zero',
  'eight two zero',
  825,
  'eight*two*five',
  'eight-two-five',
  'eight two five',
  826,
  'eight*two*six',
  'eight-two-six',
  'eight two six',
  828,
  'eight*two*eight',
  'eight-two-eight',
  'eight two eight',
  829,
  'eight*two*nine',
  'eight-two-nine',
  'eight two nine',
  830,
  'eight*three*zero',
  'eight-three-zero',
  'eight three zero',
  831,
  'eight*three*one',
  'eight-three-one',
  'eight three one',
  832,
  'eight*three*two',
  'eight-three-two',
  'eight three two',
  838,
  'eight*three*eight',
  'eight-three-eight',
  'eight three eight',
  839,
  'eight*three*nine',
  'eight-three-nine',
  'eight three nine',
  840,
  'eight*four*zero',
  'eight-four-zero',
  'eight four zero',
  843,
  'eight*four*three',
  'eight-four-three',
  'eight four three',
  845,
  'eight*four*five',
  'eight-four-five',
  'eight four five',
  847,
  'eight*four*seven',
  'eight-four-seven',
  'eight four seven',
  848,
  'eight*four*eight',
  'eight-four-eight',
  'eight four eight',
  849,
  'eight*four*nine',
  'eight-four-nine',
  'eight four nine',
  850,
  'eight*five*zero',
  'eight-five-zero',
  'eight five zero',
  854,
  'eight*five*four',
  'eight-five-four',
  'eight five four',
  856,
  'eight*five*six',
  'eight-five-six',
  'eight five six',
  857,
  'eight*five*seven',
  'eight-five-seven',
  'eight five seven',
  858,
  'eight*five*eight',
  'eight-five-eight',
  'eight five eight',
  859,
  'eight*five*nine',
  'eight-five-nine',
  'eight five nine',
  860,
  'eight*six*zero',
  'eight-six-zero',
  'eight six zero',
  862,
  'eight*six*two',
  'eight-six-two',
  'eight six two',
  863,
  'eight*six*three',
  'eight-six-three',
  'eight six three',
  864,
  'eight*six*four',
  'eight-six-four',
  'eight six four',
  865,
  'eight*six*five',
  'eight-six-five',
  'eight six five',
  867,
  'eight*six*seven',
  'eight-six-seven',
  'eight six seven',
  868,
  'eight*six*eight',
  'eight-six-eight',
  'eight six eight',
  869,
  'eight*six*nine',
  'eight-six-nine',
  'eight six nine',
  870,
  'eight*seven*zero',
  'eight-seven-zero',
  'eight seven zero',
  872,
  'eight*seven*two',
  'eight-seven-two',
  'eight seven two',
  873,
  'eight*seven*three',
  'eight-seven-three',
  'eight seven three',
  876,
  'eight*seven*six',
  'eight-seven-six',
  'eight seven six',
  878,
  'eight*seven*eight',
  'eight-seven-eight',
  'eight seven eight',
  901,
  'nine*zero*one',
  'nine-zero-one',
  'nine zero one',
  902,
  'nine*zero*two',
  'nine-zero-two',
  'nine zero two',
  903,
  'nine*zero*three',
  'nine-zero-three',
  'nine zero three',
  904,
  'nine*zero*four',
  'nine-zero-four',
  'nine zero four',
  905,
  'nine*zero*five',
  'nine-zero-five',
  'nine zero five',
  906,
  'nine*zero*six',
  'nine-zero-six',
  'nine zero six',
  907,
  'nine*zero*seven',
  'nine-zero-seven',
  'nine zero seven',
  908,
  'nine*zero*eight',
  'nine-zero-eight',
  'nine zero eight',
  909,
  'nine*zero*nine',
  'nine-zero-nine',
  'nine zero nine',
  910,
  'nine*one*zero',
  'nine-one-zero',
  'nine one zero',
  912,
  'nine*one*two',
  'nine-one-two',
  'nine one two',
  913,
  'nine*one*three',
  'nine-one-three',
  'nine one three',
  914,
  'nine*one*four',
  'nine-one-four',
  'nine one four',
  915,
  'nine*one*five',
  'nine-one-five',
  'nine one five',
  916,
  'nine*one*six',
  'nine-one-six',
  'nine one six',
  917,
  'nine*one*seven',
  'nine-one-seven',
  'nine one seven',
  918,
  'nine*one*eight',
  'nine-one-eight',
  'nine one eight',
  919,
  'nine*one*nine',
  'nine-one-nine',
  'nine one nine',
  920,
  'nine*two*zero',
  'nine-two-zero',
  'nine two zero',
  925,
  'nine*two*five',
  'nine-two-five',
  'nine two five',
  928,
  'nine*two*eight',
  'nine-two-eight',
  'nine two eight',
  929,
  'nine*two*nine',
  'nine-two-nine',
  'nine two nine',
  930,
  'nine*three*zero',
  'nine-three-zero',
  'nine three zero',
  931,
  'nine*three*one',
  'nine-three-one',
  'nine three one',
  934,
  'nine*three*four',
  'nine-three-four',
  'nine three four',
  936,
  'nine*three*six',
  'nine-three-six',
  'nine three six',
  937,
  'nine*three*seven',
  'nine-three-seven',
  'nine three seven',
  938,
  'nine*three*eight',
  'nine-three-eight',
  'nine three eight',
  939,
  'nine*three*nine',
  'nine-three-nine',
  'nine three nine',
  940,
  'nine*four*zero',
  'nine-four-zero',
  'nine four zero',
  941,
  'nine*four*one',
  'nine-four-one',
  'nine four one',
  943,
  'nine*four*three',
  'nine-four-three',
  'nine four three',
  945,
  'nine*four*five',
  'nine-four-five',
  'nine four five',
  947,
  'nine*four*seven',
  'nine-four-seven',
  'nine four seven',
  948,
  'nine*four*eight',
  'nine-four-eight',
  'nine four eight',
  949,
  'nine*four*nine',
  'nine-four-nine',
  'nine four nine',
  951,
  'nine*five*one',
  'nine-five-one',
  'nine five one',
  952,
  'nine*five*two',
  'nine-five-two',
  'nine five two',
  954,
  'nine*five*four',
  'nine-five-four',
  'nine five four',
  956,
  'nine*five*six',
  'nine-five-six',
  'nine five six',
  959,
  'nine*five*nine',
  'nine-five-nine',
  'nine five nine',
  970,
  'nine*seven*zero',
  'nine-seven-zero',
  'nine seven zero',
  971,
  'nine*seven*one',
  'nine-seven-one',
  'nine seven one',
  972,
  'nine*seven*two',
  'nine-seven-two',
  'nine seven two',
  973,
  'nine*seven*three',
  'nine-seven-three',
  'nine seven three',
  978,
  'nine*seven*eight',
  'nine-seven-eight',
  'nine seven eight',
  979,
  'nine*seven*nine',
  'nine-seven-nine',
  'nine seven nine',
  980,
  'nine*eight*zero',
  'nine-eight-zero',
  'nine eight zero',
  983,
  'nine*eight*three',
  'nine-eight-three',
  'nine eight three',
  984,
  'nine*eight*four',
  'nine-eight-four',
  'nine eight four',
  985,
  'nine*eight*five',
  'nine-eight-five',
  'nine eight five',
  986,
  'nine*eight*six',
  'nine-eight-six',
  'nine eight six',
  989,
  'nine*eight*nine',
  'nine-eight-nine',
  'nine eight nine',
];
