/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cd0e4457-6d32-4572-afdb-0ef0c461a4ce",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_R43n4MTOT",
    "aws_user_pools_web_client_id": "2h82cmt466rphvds5se9ebgqms",
    "oauth": {
        "domain": "greenlync-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "greenlync://",
        "redirectSignOut": "greenlync://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE",
        "APPLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "on-the-fly-video-convert-greenlync-src-004920813224",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
