const images = {
  creditCardFront: require('./resources/card-front.png'),
  creditCardBack: require('./resources/card-back.png'),
  agePrivacyBg: require('./resources/age-privacy-confirmation/agePrivacyBg.png'),
  greenLyncLogo: require('./resources/age-privacy-confirmation/greenLyncLogo.png'),
  facebookSignUpLogo: require('./resources/register/facebookSignUpLogo.png'),
  appleSignUpLogo: require('./resources/register/appleSignUpLogo.png'),
  googleSignUpLogo: require('./resources/register/googleSignUpLogo.png'),
  instagramSignUpLogo: require('./resources/register/instagramSignUpLogo.png'),
  checkMark: require('./resources/register/checkMark.png'),
  medium: require('./resources/notification/Medium.png'),
  vector: require('./resources/notification/Vector.png'),
  art: require('./resources/notification/Art.png'),
  notify: require('./resources/notification/Vectorr.png'),
  delete: require('./resources/notification/Vector3.png'),

  chatIcon: require('./resources/feed/chat.png'),
  notificationIcon: require('./resources/feed/notification.png'),
  commentIcon: require('./resources/feed/comment-gray.png'),
  emptyFeedImage: require('./resources/feed/empty-feed.png'),

  //Loader
  loader: require('./resources/loader.gif'),

  //trending screen
  share: require('./resources/trending/share.png'),
  play: require('./resources/trending/play.png'),
  commentBorder: require('./resources/trending/comment-border.png'),
  commentFilled: require('./resources/trending/comment-filled.png'),
  verticalDots: require('./resources/trending/vertical-dots.png'),
  smiley: require('./resources/trending/smiley.png'),
  horizontalDots: require('./resources/trending/horizontal-dots.png'),
  aboutDummyImage: require('./resources/shop/about.png'),
  locationMarker: require('./resources/shop/location.png'),
  locationMarker1: require('./resources/shop/location1.png'),
  dummyImage1: require('./resources/dummy/dummyImage.png'),
  dummyImage2: require('./resources/dummy/dummyImage2.png'),
  dummyImage3: require('./resources/dummy/dummyImage3.png'),
  dummyImage4: require('./resources/dummy/dummyImage4.png'),
  placeHolderImage: require('./resources/trending/imgPlaceholder.png'),
  //shop screen
  back: require('../images/resources/shop/back.png'),
  case: require('../images/resources/shop/case.png'),
  clock: require('../images/resources/shop/clock.png'),
  filter: require('../images/resources/shop/filter.png'),
  heartBorder: require('../images/resources/shop/heartBorder.png'),
  delivery: require('../images/resources/shop/dilevery.png'),
  dispensary: require('../images/resources/shop/dispensary.png'),
  doctor: require('../images/resources/shop/doctorlocation.png'),
  call: require('../images/resources/shop/call.png'),

  information: require('../images/resources/shop/information.png'),
  mapIcon: require('../images/resources/shop/mapIcon.png'),
  markerDark: require('../images/resources/shop/markerDark.png'),
  markerGray: require('../images/resources/shop/markerGray.png'),
  heartFilled: require('../images/resources/shop/heartFill.png'),
  starFilled: require('../images/resources/shop/starFill.png'),

  markerLight: require('../images/resources/shop/markerLight.png'),
  markerCircle: require('../images/resources/shop/markerCircle.png'),
  markerGreen: require('../images/resources/shop/markerGreen.png'),
  more: require('../images/resources/shop/more.png'),
  search: require('../images/resources/shop/search.png'),

  // notification
  system: require('../images/resources/notification/system.png'),
  comment: require('../images/resources/notification/comment.png'),
  like: require('../images/resources/notification/like.png'),
  addFriend: require('../images/resources/notification/addFriend.png'),
  newComment: require('../images/resources/notification/newComment.png'),
  newLike: require('../images/resources/notification/newLike.png'),
  newHighFive: require('../images/resources/notification/highFive.png'),
  //more menu
  calender: require('../images/resources/more-menu/calender.png'),
  cannabis: require('../images/resources/more-menu/cannabis.png'),
  contest: require('../images/resources/more-menu/contest.png'),
  dating: require('../images/resources/more-menu/dating.png'),
  fire: require('../images/resources/more-menu/fire.png'),
  greenTalk: require('../images/resources/more-menu/greenTalk.png'),
  dp: require('../images/resources/trending/dp.jpeg'),
  moreGreen: require('../images/resources/more-menu/more.png'),
  moreBlack: require('../images/resources/more-menu/moreBlack.png'),

  // chat
  crossEdit: require('../images/resources/chat/crossEdit.png'),
  chatBackImage: require('../images/resources/chat/chatBackImage.png'),
  videoCall: require('../images/resources/chat/videoCall.png'),
  voiceCall: require('../images/resources/chat/voiceCall.png'),
  dotMenu: require('../images/resources/chat/dotMenu.png'),
  chatBackImage2: require('../images/resources/chat/chatBackImage2.png'),
  link: require('../images/resources/chat/link.png'),
  camera: require('../images/resources/chat/camera.png'),
  text: require('../images/resources/chat/text.png'),
  emoji: require('../images/resources/chat/emoji.png'),
  groupDP: require('../images/resources/chat/groupDP.jpeg'),
  plus: require('../images/resources/chat/plus.png'),
  cross: require('../images/resources/chat/cross.png'),
  addMember: require('../images/resources/chat/addMember.png'),
  send: require('../images/resources/chat/send.png'),
  list: require('../images/resources/shop/list.png'),
  cancel: require('../images/resources/chat/cancel.png'),
  groupChat: require('./resources/chat/group-chat.png'),
  message: require('./resources/chat/message.png'),
  group_added: require('./resources/notification/1647547.png'),
  mentions: require('./resources/notification/mentions.png'),
  zeroNotification: require('./resources/notification/zeroNotification.jpg'),
  svg: require('./resources/notification/svg.png'),
  joint_new: require('./resources/notification/joint_new.png'),

  // markers
  delivery_32: require('./resources/shop/markers/delivery-32.png'),
  delivery_40: require('./resources/shop/markers/delivery-40.png'),
  delivery_48: require('./resources/shop/markers/delivery-48.png'),
  delivery_56: require('./resources/shop/markers/delivery-56.png'),
  delivery_64: require('./resources/shop/markers/delivery-64.png'),

  dispensary_32: require('./resources/shop/markers/dispensary-32.png'),
  dispensary_40: require('./resources/shop/markers/dispensary-40.png'),
  dispensary_48: require('./resources/shop/markers/dispensary-48.png'),
  dispensary_56: require('./resources/shop/markers/dispensary-56.png'),
  dispensary_64: require('./resources/shop/markers/dispensary-64.png'),
  dispensary_v2: require('./resources/shop/markers/dispensary_v2.png'),

  doctor_32: require('./resources/shop/markers/doctor-32.png'),
  doctor_40: require('./resources/shop/markers/doctor-40.png'),
  doctor_48: require('./resources/shop/markers/doctor-48.png'),
  doctor_56: require('./resources/shop/markers/doctor-56.png'),
  doctor_64: require('./resources/shop/markers/doctor-64.png'),

  shpMenuIcon: require('./resources/shop/markers/shpMenuIcon.png'),

  placeHolder: require('./resources/shop/markers/placeHolder.png'),
  directions: require('./resources/shop/markers/direction.png'),
  web: require('./resources/shop/icons/web.png'),
  locationMakr: require('./resources/shop/icons/location.png'),
  clockMark: require('./resources/shop/icons/clock.png'),
  down: require('./resources/shop/icons/down.png'),
  up: require('./resources/shop/icons/up.png'),

  updateImage: require('./resources/update/updateImage.png'),
  cancelImage: require('./resources/update/cancel.png'),
  follow: require('./resources/profile/follow.png'),
  vip: require('./resources/profile/vipcard.png'),

  //trending buttons
  searchButton: require('./resources/trending/search.png'),
  mainButton: require('./resources/trending/mainButton.png'),
  chat_circular_icon: require('./resources/trending/chat_circular_menu.png'),
  chat_icon_in_profile: require('./resources/trending/chat_icon_in_profile.png'),
  chat_new_black: require('./resources/trending/chat_new_black.png'),
  fillgallery: require('../images/resources/chat/fillGallery.png'),
  flamStroke: require('../images/resources/feed/flameStroke.png'),
  mute: require('../images/resources/feed/mute.png'),
  volume: require('../images/resources/feed/volume.png'),
  posting: require('../images/resources/feed/POSTING.png'),
  theJointFinal: require('../images/resources/feed/jointfinaldesing.png'),
  home: require('../images/resources/feed/home.png'),

  //block user empty
  blockUserEmpty: require('../images/block-user/block-user-empty.png'),
  location: require('../images/resources/profile/location.png'),
  edit: require('../images/resources/profile/edit.png'),
  verifyIcon: require('../images/resources/profile/verifyIcon.png'),
  gallery: require('../images/resources/feed/gallery.png'),

  //Auth
  restorePassword: require('../images/resources/auth/restorandverificationimage.jpg'),
  signUp: require('../images/resources/auth/signupimage.jpg'),
  logIn: require('../images/resources/auth/loginimage.jpg'),
  posttoJoint: require('../images/resources/feed/thejoint.jpg'),
  posttoGreen: require('../images/resources/feed/greentalk.jpg'),
  notification: require('../images/resources/feed/notifications.jpg'),
  blocked: require('../images/resources/profile/blocked.png'),

  placeHolderShop: require('../images/resources/shop/icons/placeHolder.png'),
};

export default images;
